import { useState } from 'react';
import { Terminal, Copy, Check, Download, ExternalLink, Sparkles } from 'lucide-react';
import type { VideoSettings, Template } from '../../types';

interface CLIWorkflowProps {
  uploadedImage: { url: string; file: File } | null;
  selectedTemplate: Template | null;
  settings: VideoSettings;
}

export default function CLIWorkflow({ uploadedImage, selectedTemplate, settings }: CLIWorkflowProps) {
  const [copied, setCopied] = useState(false);

  const cliCommands = `# PixVerse CLI Video Generation
# Generated by Shortcutsystem

# Step 1: Login to PixVerse (if not already logged in)
pixverse auth login

# Step 2: Upload your image
pixverse image upload --file "${uploadedImage?.file.name || 'your-image.jpg'}"

# Step 3: Generate video using PixVerse V6
pixverse generate \\
  --model v6 \\
  --duration ${settings.duration} \\
  --quality ${settings.quality} \\
  --motion-mode ${settings.motionMode} \\
  --aspect-ratio ${settings.aspectRatio} \\
  --prompt "${settings.prompt}" \\
  ${settings.negativePrompt ? `--negative-prompt "${settings.negativePrompt}"` : ''}

# Alternative: Using image URL directly
pixverse generate \\
  --image-url "${uploadedImage?.url || 'https://your-image-url.com/image.jpg'}" \\
  --model v6 \\
  --duration ${settings.duration} \\
  --prompt "${settings.prompt}"`;

  const configJson = JSON.stringify({
    model: settings.model,
    duration: settings.duration,
    quality: settings.quality,
    motion_mode: settings.motionMode,
    aspect_ratio: settings.aspectRatio,
    prompt: settings.prompt,
    negative_prompt: settings.negativePrompt,
    template: selectedTemplate?.name || 'custom',
    generated_at: new Date().toISOString(),
  }, null, 2);

  const handleCopyCommands = async () => {
    try {
      await navigator.clipboard.writeText(cliCommands);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const handleDownloadConfig = () => {
    const blob = new Blob([configJson], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'pixverse-config.json';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadScript = () => {
    const script = `#!/bin/bash
# PixVerse Video Generation Script
# Generated by Shortcutsystem

echo "Starting PixVerse Video Generation..."
echo "Model: ${settings.model}"
echo "Duration: ${settings.duration}s"
echo "Quality: ${settings.quality}"

# Login
echo "Logging in to PixVerse..."
pixverse auth login

# Upload image (replace with your image path)
echo "Uploading image..."
pixverse image upload --file "./your-image.jpg"

# Generate video
echo "Generating video with PixVerse V6..."
pixverse generate \\
  --model v6 \\
  --duration ${settings.duration} \\
  --quality ${settings.quality} \\
  --motion-mode ${settings.motionMode} \\
  --aspect-ratio ${settings.aspectRatio} \\
  --prompt "${settings.prompt}"

echo "Video generation complete!"
`;
    const blob = new Blob([script], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'generate-video.sh';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <div className="text-center mb-8">
        <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-accent/10 flex items-center justify-center">
          <Terminal className="w-8 h-8 text-accent" />
        </div>
        <h2 className="text-2xl font-bold mb-2">Generate with PixVerse CLI</h2>
        <p className="text-text-secondary">
          Copy the commands below and run them in your terminal
        </p>
      </div>

      {/* Settings Summary */}
      <div className="p-4 rounded-xl bg-secondary border border-border">
        <h3 className="font-semibold mb-3 flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-accent" />
          Your Video Settings
        </h3>
        <div className="grid grid-cols-2 gap-3 text-sm">
          <div>
            <span className="text-text-muted">Template:</span>
            <span className="ml-2 font-medium">{selectedTemplate?.name || 'Custom'}</span>
          </div>
          <div>
            <span className="text-text-muted">Model:</span>
            <span className="ml-2 font-medium">{settings.model}</span>
          </div>
          <div>
            <span className="text-text-muted">Duration:</span>
            <span className="ml-2 font-medium">{settings.duration}s</span>
          </div>
          <div>
            <span className="text-text-muted">Quality:</span>
            <span className="ml-2 font-medium">{settings.quality}</span>
          </div>
          <div className="col-span-2">
            <span className="text-text-muted">Aspect:</span>
            <span className="ml-2 font-medium">{settings.aspectRatio}</span>
          </div>
        </div>
      </div>

      {/* CLI Commands */}
      <div className="rounded-xl bg-primary border border-border overflow-hidden">
        <div className="flex items-center justify-between px-4 py-3 bg-secondary border-b border-border">
          <div className="flex items-center gap-2">
            <Terminal className="w-4 h-4 text-accent" />
            <span className="text-sm font-medium">Terminal Commands</span>
          </div>
          <button
            onClick={handleCopyCommands}
            className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-white/5 hover:bg-white/10 text-sm transition-colors"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-success" />
                Copied!
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                Copy
              </>
            )}
          </button>
        </div>
        <pre className="p-4 text-sm font-mono overflow-x-auto">
          <code className="text-text-secondary">{cliCommands}</code>
        </pre>
      </div>

      {/* Download Options */}
      <div className="flex flex-wrap gap-3">
        <button
          onClick={handleDownloadConfig}
          className="flex items-center gap-2 px-4 py-2 rounded-lg bg-white/5 hover:bg-white/10 text-sm transition-colors"
        >
          <Download className="w-4 h-4" />
          Download Config JSON
        </button>
        <button
          onClick={handleDownloadScript}
          className="flex items-center gap-2 px-4 py-2 rounded-lg bg-white/5 hover:bg-white/10 text-sm transition-colors"
        >
          <Download className="w-4 h-4" />
          Download Shell Script
        </button>
      </div>

      {/* Instructions */}
      <div className="p-4 rounded-xl bg-accent/5 border border-accent/20">
        <h3 className="font-semibold mb-3">How to use:</h3>
        <ol className="space-y-2 text-sm text-text-secondary">
          <li className="flex gap-3">
            <span className="w-6 h-6 rounded-full bg-accent text-primary text-xs flex items-center justify-center flex-shrink-0">1</span>
            <span>Make sure you've installed PixVerse CLI: <code className="px-1.5 py-0.5 rounded bg-white/10 text-accent">npm install -g pixverse</code></span>
          </li>
          <li className="flex gap-3">
            <span className="w-6 h-6 rounded-full bg-accent text-primary text-xs flex items-center justify-center flex-shrink-0">2</span>
            <span>Login to PixVerse: <code className="px-1.5 py-0.5 rounded bg-white/10 text-accent">pixverse auth login</code></span>
          </li>
          <li className="flex gap-3">
            <span className="w-6 h-6 rounded-full bg-accent text-primary text-xs flex items-center justify-center flex-shrink-0">3</span>
            <span>Copy the commands above or download the script</span>
          </li>
          <li className="flex gap-3">
            <span className="w-6 h-6 rounded-full bg-accent text-primary text-xs flex items-center justify-center flex-shrink-0">4</span>
            <span>Replace <code className="px-1.5 py-0.5 rounded bg-white/10 text-accent">your-image.jpg</code> with your actual image path</span>
          </li>
          <li className="flex gap-3">
            <span className="w-6 h-6 rounded-full bg-accent text-primary text-xs flex items-center justify-center flex-shrink-0">5</span>
            <span>Paste and run the commands in your terminal</span>
          </li>
        </ol>
      </div>

      {/* Resources */}
      <div className="flex flex-wrap gap-3">
        <a
          href="https://github.com/PixVerseAI/skills"
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center gap-2 px-4 py-2 rounded-lg bg-white/5 hover:bg-white/10 text-sm transition-colors"
        >
          <ExternalLink className="w-4 h-4" />
          PixVerse Skills Repository
        </a>
        <a
          href="https://platform.pixverse.ai"
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center gap-2 px-4 py-2 rounded-lg bg-white/5 hover:bg-white/10 text-sm transition-colors"
        >
          <ExternalLink className="w-4 h-4" />
          PixVerse Platform
        </a>
      </div>
    </div>
  );
}
